workflows:
  android-build:
    name: Android Build
    scripts:
      - name: Build Release APK
        script: | 
          cd
RealTimeGameTranslator_beautiful
          chmod +x ./gradlew
          ./gradlew clean
assembleRelease --no-daemon
    artifacts:
      - 
RealTimeGameTranslator_beautiful/app/
build/outputs/**/*.apk
